#!/bin/bash
# Get the current Vercel domain from environment or ask user

echo "🔧 RealMint Vercel → Render CORS Configuration"
echo ""
echo "Your current Vercel deployment URL:"
echo "  https://realmint-platform-atjvqsbaw-arnolds-projects-3ff63785.vercel.app"
echo ""
echo "To enable API communication, you need to add this domain to Render's ALLOWED_ORIGINS."
echo ""
echo "📋 Steps to fix:"
echo ""
echo "1. Go to: https://dashboard.render.com/"
echo "2. Click on 'realmint-api' service"
echo "3. Go to 'Environment' tab"
echo "4. Find or create the variable: ALLOWED_ORIGINS"
echo "5. Set it to (replace with YOUR Vercel URL if different):"
echo ""
echo "   ALLOWED_ORIGINS=https://realmint-platform-atjvqsbaw-arnolds-projects-3ff63785.vercel.app,http://localhost:3000,http://localhost:5173,http://127.0.0.1:5173"
echo ""
echo "6. Click 'Save'"
echo "7. Wait for Render to redeploy (about 30 seconds)"
echo "8. Refresh your Vercel app"
echo "9. Check DevTools Console for [apiClient] logs showing successful requests"
echo ""
echo "⚠️  Important: Copy the EXACT Vercel URL including the random hash"
echo ""
